global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'integr8'
    static_configs:
      - targets: ['node:10000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo:27017']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']